config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "restaurants#index"

  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  validates :name, length: {minimum: 3}, uniqueness: true

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def average_rating
    return 'N/A' if reviews.none?
    reviews.inject(0) {|memo, review| memo + review.rating} / reviews.count
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  validates :rating, inclusion: (1..5)
  has_many :endorsements
end

app/models/user.rb
class User < ActiveRecord::Base
  #include default devise modules.
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :reviews

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/models/users.rb
#class User < ActiveRecord::Base
#  #include default devise modules.
#  devise :database_authenticatable, :registerable,
#         :recoverable, :rememberable, :trackable, :validatable,
#         :omniauthable, :omniauth_probiders => [:facebook]
#
#  def self.from_omniauth(auth)
#    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
#      user.email = auth.info.email
#      user.password = Devise.friendly_token[0,20]
#    end
#  end
#end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  include ActionView::Helpers::TextHelper

  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: {new_endorsement_count: @review.endorsements.count}, js:"window.location.pathname'restaurants_path'"
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end


  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end

    private

    def restaurant_params
      params.require(:restaurant).permit(:name, :image)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
      @restaurant = Restaurant.find(params[:restaurant_id])
      @restaurant.reviews.create(review_params)
      redirect_to restaurants_path
  end

  def review_params
      params.require(:review).permit(:thoughts, :rating)
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = 6 - rating
    "★" * rating + '☆' * remainder
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpCloneRails</title>
  <meta charset = "UTF-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, html: {multipart: true} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form" %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>

    <h2> <%= link_to "#{restaurant.name}", restaurant_path(restaurant) %> </h2>
    <%= image_tag restaurant.image.url(:thumb) %>
    <h3> Average rating: <%= star_rating(restaurant.average_rating) %> </h3>
    <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>

    <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>

    <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>

    <h3>Reviews for <%= restaurant.reviews.any? %>
      <% if @restaurants.any? %>
        <ul>
          <% restaurant.reviews.each do |review| %>
            <li>
              <%= review.thoughts %>, <strongt><%= review.rating %></strong>/5
              <p>
                <%= link_to "Endorse", review_endorsements_path(review), class: 'endorsements-link' %>
                <span class="endorsements_count"> <%= review.endorsements.count %> </span>
                <% if review.endorsements.count < 2 %>
                  endorsement
                <% else %>
                  endorsements
                <% end %>
              </p>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>No reviews.</p>
      <% end %>
    <% end %>

<% else %>
  No restaurants yet
<% end %>


<a href='/restaurants/new'>Add a restaurant</a>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <div id="errors" >
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render "form" %>

app/views/restaurants/show.html.erb
<p> <%= @restaurant.name %> </p>
<p> <%= @restaurant.description %> </p>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>